# Generated by Django 2.1.1 on 2018-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('selfMedia', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('depart', models.CharField(max_length=50)),
            ],
        ),
    ]
